### ISSUE TITLE
For High End Pc the game runs badly.

### ISSUE THREAD

**Issue by DaniSmech** [NameLord/Reyna-Valorant-Clone#12]
title

**Comment by NameLord** [comment]
Need more informations

**Comment by DaniSmech** [comment]
![image](https://user-images.githubusercontent.com/84475671/120940304-44fbc480-c725-11eb-8117-3518ba2d7b44.png)
![image](https://user-images.githubusercontent.com/84475671/120940317-52b14a00-c725-11eb-8329-770722af1b05.png)

**Comment by NameLord** [comment]
We don't know why this happens but we will find a way.
Thanks for the cooperation.
