### ISSUE TITLE
Release When?

### ISSUE THREAD

**Issue by DaniSmech** [NameLord/Reyna-Valorant-Clone#25]
Please? when it will be released 0.0.1.1 ?

**Comment by NameLord** [comment]
There will be but first of all we need to fix all the bugs + new features into the game then we can release the 0.0.1.1.

**Comment by DaniSmech** [comment]
Dude why is it taking so long?

**Comment by NameLord** [comment]
I cannot provide you why is it taking so long, Sorry.
